-- supabase/schema.sql
--
-- Postgres schema for the claw-machine-manager backend, translated 1:1 from
-- the Google Sheets structure defined in apps-script/Db.gs (SCHEMA / HEADER_LABELS).
-- This is phase 1 of the Supabase migration (see supabase/MIGRATION_PLAN.md) —
-- schema only, no data, no application logic yet.
--
-- Design choices, kept close to the existing system on purpose so the port
-- from Service.gs/Reports.gs stays low-risk:
--   - IDs stay as the existing text ids (e.g. 'usr_xxxxx', 'mch_xxxxx',
--     generated by newId() in Db.gs) instead of switching to uuid — the
--     current codebase generates and compares these ids as strings
--     everywhere, and there is no reason to also rewrite id generation
--     while also rewriting storage.
--   - No archiving/partitioning table split (the "封存_2026Q1" style extra
--     sheets in Db.gs/Archive.gs) — that trick existed purely to work around
--     Sheets reading the whole table on every request. A real database with
--     indexes on (machine_id, business_date) does not need it; records just
--     stays one table forever. carry_in/out/prize/chip_in/chip_out columns
--     on machines are kept for the migration itself (see MIGRATION_PLAN.md)
--     but the running system will not need to add to them going forward.
--   - Row Level Security is enabled on every table but left with NO policies
--     yet. This app has its own username/password + session-token auth, not
--     Supabase Auth — see "Auth & RLS" in MIGRATION_PLAN.md before writing
--     policies; do not flip these tables open without policies in place.

-- ── users ───────────────────────────────────────────────

create table if not exists users (
  user_id        text primary key,
  username       text not null unique,
  display_name   text not null default '',
  password_hash  text not null,
  salt           text not null,
  role           text not null check (role in ('admin', 'patrol', 'owner')),
  status         text not null default 'active' check (status in ('active', 'disabled')),
  created_at     timestamptz not null default now(),
  last_login_at  timestamptz
);

-- ── machines ────────────────────────────────────────────

create table if not exists machines (
  machine_id      text primary key,
  name            text not null,
  location        text not null default '',
  status          text not null default 'running' check (status in ('running', 'maintenance', 'offline')),
  color           text not null default '#4F7BE8',
  sort_order      numeric not null default 0,
  note            text not null default '',
  created_at      timestamptz not null default now(),
  category        text not null default 'dice' check (category in ('dice', 'electronic')),
  icon            text not null default 'classic',
  -- 封存前累計——遷移用欄位，見上面的說明；遷移完成、Records 全部搬進來
  -- 之後這幾欄只是歷史保留，程式邏輯不會再往上加。
  carry_in        numeric not null default 0,
  carry_out       numeric not null default 0,
  carry_prize     numeric not null default 0,
  carry_chip_in   numeric not null default 0,
  carry_chip_out  numeric not null default 0
);

-- ── records（單一最重要、資料量最大的表；所有查詢熱點都靠索引）──

create table if not exists records (
  record_id      text primary key,
  machine_id     text not null references machines(machine_id),
  type           text not null check (type in ('in', 'out', 'prize', 'chip_in', 'chip_out')),
  amount         numeric not null default 0,
  prize_id       text,
  prize_name     text not null default '',
  unit_amount    numeric,
  count          numeric,
  user_id        text not null references users(user_id),
  created_at     timestamptz not null default now(),
  note           text not null default '',
  voided         boolean not null default false,
  voided_by      text,
  voided_at      timestamptz,
  client_token   text not null unique, -- 冪等鍵，對應 addRecord 的 clientToken 去重機制
  meter_start    numeric,
  meter_end      numeric,
  business_date  date not null -- 記帳當下 snapshot 好的營業日期，見 Service.gs 的 _currentBusinessDate()
);

-- 熱路徑：dashboard/machineDetail/report 幾乎每一支都是「某機台 + 某日期
-- 區間」，這支索引取代掉原本 Sheets 靠季度封存縮小表格的整套機制。
create index if not exists records_machine_business_date_idx
  on records (machine_id, business_date);
-- 「不看哪一台機台、全部機台合併算」的查詢（report 不指定 machineId、
-- 或 exportLedgerGrids 那種分類查詢）用得到。
create index if not exists records_business_date_idx
  on records (business_date);
create index if not exists records_voided_idx
  on records (voided) where voided = false;

-- ── prizes ──────────────────────────────────────────────

create table if not exists prizes (
  prize_id    text primary key,
  machine_id  text not null references machines(machine_id),
  name        text not null,
  amount      numeric not null default 0,
  sort_order  numeric not null default 0,
  active      boolean not null default true
);

create index if not exists prizes_machine_idx on prizes (machine_id);

-- ── quick_amounts ───────────────────────────────────────

create table if not exists quick_amounts (
  qa_id       text primary key,
  machine_id  text not null references machines(machine_id),
  type        text not null check (type in ('in', 'out')),
  amount      numeric not null,
  label       text not null default '',
  sort_order  numeric not null default 0
);

create index if not exists quick_amounts_machine_idx on quick_amounts (machine_id);

-- ── meter_rates ─────────────────────────────────────────

create table if not exists meter_rates (
  rate_id     text primary key,
  machine_id  text not null default '', -- 空字串＝全局預設，跟 Db.gs 原本的用法一致
  rate        numeric not null default 100
);

create index if not exists meter_rates_machine_idx on meter_rates (machine_id);

-- ── permissions（台主看得到哪些機台）────────────────────

create table if not exists permissions (
  user_id      text not null references users(user_id),
  machine_id   text not null references machines(machine_id),
  granted_by   text references users(user_id),
  granted_at   timestamptz not null default now(),
  primary key (user_id, machine_id)
);

-- ── sessions（登入 token）────────────────────────────────
--
-- 遷移時故意跟其他表分開處理：這張表本來就設計成短生命週期、高頻率
-- 讀寫（每一支 API 幾乎都要驗一次 token），改天如果要換掉現在的自製
-- session 機制、改用 Supabase Auth，這張表整個會被取代，不需要遷移
-- 資料過去。

create table if not exists sessions (
  token        text primary key,
  user_id      text not null references users(user_id),
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null,
  remember     boolean not null default false
);

create index if not exists sessions_user_idx on sessions (user_id);
create index if not exists sessions_expires_idx on sessions (expires_at);

-- ── config（系統設定，key-value）─────────────────────────

create table if not exists config (
  key    text primary key,
  value  text not null default ''
);

-- ── biz_days（手動營業日 session，處理跨夜）──────────────

create table if not exists biz_days (
  biz_id         text primary key,
  business_date  date not null,
  opened_at      timestamptz not null,
  opened_by      text references users(user_id),
  closed_at      timestamptz,
  closed_by      text references users(user_id),
  auto_closed    boolean not null default false
);

create index if not exists biz_days_open_idx on biz_days (closed_at) where closed_at is null;
create index if not exists biz_days_business_date_idx on biz_days (business_date);

-- ── daily_ledger（每日手動帳目：週轉金／台主給／台主領…）─

create table if not exists daily_ledger (
  ledger_id              text primary key,
  business_date          date not null,
  turnover               numeric not null default 0,
  transport              numeric not null default 0, -- 舊欄位，已經用不到，保留讀舊資料
  given_to_owner         numeric not null default 0,  -- 舊欄位，已改用 given_to_owner_items
  taken_by_owner         numeric not null default 0,  -- 舊欄位，已改用 taken_by_owner_items
  returned_to_house      numeric not null default 0,  -- 舊欄位，已經用不到，保留讀舊資料
  updated_by             text references users(user_id),
  updated_at             timestamptz not null default now(),
  biz_id                 text references biz_days(biz_id),
  manual_432             numeric not null default 0,
  manual_441             numeric not null default 0,
  given_to_owner_items   jsonb not null default '[]'::jsonb, -- [{name, amount}, ...]
  taken_by_owner_items   jsonb not null default '[]'::jsonb,
  manual_expense         numeric not null default 0
);

create index if not exists daily_ledger_business_date_idx on daily_ledger (business_date);

-- ── Row Level Security ──────────────────────────────────
--
-- 先全部開啟、不加任何 policy（預設就是全擋，安全的起始狀態）。實際
-- policy 要等 MIGRATION_PLAN.md「Auth & RLS」那節決定的走法定案才補上，
-- 現在寫死的話遷移過程中很可能要整套重寫。

alter table users           enable row level security;
alter table machines        enable row level security;
alter table records         enable row level security;
alter table prizes          enable row level security;
alter table quick_amounts   enable row level security;
alter table meter_rates     enable row level security;
alter table permissions     enable row level security;
alter table sessions        enable row level security;
alter table config          enable row level security;
alter table biz_days        enable row level security;
alter table daily_ledger    enable row level security;
